ARG BASE_IMAGE=rust:1.72.0-slim-buster

FROM $BASE_IMAGE as builder
WORKDIR app
COPY . .
RUN cargo build --release
CMD ["./target/release/hello"]

FROM $BASE_IMAGE
COPY --from=builder /app/target/release/hello /
CMD ["./hello"]
